export const roomCards = [
  {
    id: 1,
    title: "Suite Valley",
    image: "/room-img.jpg",
    capacity: "3 Person",
    bed: "1 Large Bedroom",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-valley",
    bookNowLink: "/booking/suite-valley",
  },
  {
    id: 2,
    title: "Pine Valley",
    image: "/room-img.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-valley",
    bookNowLink: "/booking/pine-valley",
  },
  {
    id: 3,
    title: "Pine Woods",
    image: "/room-img.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-woods",
    bookNowLink: "/booking/pine-woods",
  },
  {
    id: 4,
    title: "Suite Woods",
    image: "/room-img.jpg",
    capacity: "3 Person",
    bed: "1 Bedroom + Living Area",
    kitchen: "1 Kitchen",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-woods",
    bookNowLink: "/booking/suite-woods",
  },
];
export const heroContent = [
  {
    title: "Welcome to Ramante Homes",
    subtitle: "Luxury homestays in the heart of Dehradun",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view.jpg",
  },
  {
    title: "Welcome to Ramante Homes",
    subtitle: "Luxury homestays in the heart of Dehradun",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view.jpg",
  },
  {
    title: "Welcome to Ramante Homes",
    subtitle: "Luxury homestays in the heart of Dehradun",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view.jpg",
  },
];
export const galleryImgs = [
  "/gallery/exterior1.jpg",
  "/gallery/exterior2.jpg",
  "/gallery/interior1.jpg",
  "/gallery/interior2.jpg",
  "/gallery/exterior1.jpg",
  "/gallery/exterior2.jpg",
  "/gallery/interior1.jpg",
  "/gallery/interior2.jpg",
  "/gallery/exterior1.jpg",
  "/gallery/exterior2.jpg",
  "/gallery/interior1.jpg",
  "/gallery/interior2.jpg",
];
