export const roomCards = [
  {
    id: 1,
    title: "Suite Valley",
    image: "/room.jpg",
    capacity: "3 Person",
    bed: "1 Large Bedroom",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-valley",
    bookNowLink: "/booking/suite-valley",
  },
  {
    id: 2,
    title: "Pine Valley",
    image: "/room1.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-valley",
    bookNowLink: "/booking/pine-valley",
  },
  {
    id: 3,
    title: "Pine Woods",
    image: "/room2.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-woods",
    bookNowLink: "/booking/pine-woods",
  },
  {
    id: 4,
    title: "Suite Woods",
    image: "/room3.jpg",
    capacity: "3 Person",
    bed: "1 Bedroom + Living Area",
    kitchen: "1 Kitchen",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-woods",
    bookNowLink: "/booking/suite-woods",
  },
  {
    id: 5,
    title: "Suite Valley",
    image: "/room4.jpg",
    capacity: "3 Person",
    bed: "1 Large Bedroom",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-valley",
    bookNowLink: "/booking/suite-valley",
  },
  {
    id: 6,
    title: "Pine Valley",
    image: "/room5.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-valley",
    bookNowLink: "/booking/pine-valley",
  },
  {
    id: 7,
    title: "Pine Woods",
    image: "/room6.jpg",
    capacity: "2 Person",
    bed: "1 DoubleBed",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/pine-woods",
    bookNowLink: "/booking/pine-woods",
  },
  {
    id: 8,
    title: "Suite Woods",
    image: "/room7.jpg",
    capacity: "3 Person",
    bed: "1 Bedroom + Living Area",
    kitchen: "1 Kitchen",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-woods",
    bookNowLink: "/booking/suite-woods",
  },
  {
    id: 9,
    title: "Suite Valley",
    image: "/room8.jpg",
    capacity: "3 Person",
    bed: "1 Large Bedroom",
    bathroom: "1 Bathroom",
    readMoreLink: "/rooms/suite-valley",
    bookNowLink: "/booking/suite-valley",
  },
];
export const heroContent = [
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view1.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view2.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view3.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view4.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view5.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view6.jpg",
  },
  {
    title: "Welcome to Kedar Darshan & Umesh Homestay",
    subtitle: "Luxury homestays in the heart of Rudraprayag",
    ctaText: "Book Now",
    ctaLink: "./apartments/apartments",
    imgSrc: "/outer-view7.jpg",
  },
];
export const galleryImgs = [
  "/gallery.jpg",
  "/gallery1.jpg",
  "/gallery2.jpg",
  "/bathroom.jpg",
  "/bathroom1.jpg",
  "/bathroom2.jpg",
  "/bathroom3.jpg",
  "/bathroom4.jpg",
  "/outer-view.jpg",
  "/outer-view1.jpg",
  "/outer-view4.jpg",
  "/room1.jpg",
  "/room4.jpg",
  "/room6.jpg",
];
